# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectBackup < Formula
  desc "Fast S3 Tools built in GoLang Using Multiparts and Concurrency"
  homepage ""
  version ".0.0.18"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sethkor/connect-backup/releases/download/v.0.0.18/connect-backup_.0.0.18_Darwin_amd64.tar.gz"
    sha256 "f9a551074cf076b56f0ab9c9b5b659dde6905cd0ff5af44b8c47833a03e55a57"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sethkor/connect-backup/releases/download/v.0.0.18/connect-backup_.0.0.18_Linux_amd64.tar.gz"
      sha256 "fcd9b7ea8a7c200cfee8caab1af12694d6be8ea7c8723bf750baae7c102504a4"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sethkor/connect-backup/releases/download/v.0.0.18/connect-backup_.0.0.18_Linux_arm64.tar.gz"
        sha256 "7021d34b76649c14687e0d94b3e3603dc0390c2519852797865b719aeeda8d8f"
      else
        url "https://github.com/sethkor/connect-backup/releases/download/v.0.0.18/connect-backup_.0.0.18_Linux_armv6.tar.gz"
        sha256 "22a265b4dd716727714c5df1cbdd90665c984a73d9dd1ac76965832d578e267b"
      end
    end
  end

  def install
    bin.install "connect-backup"
  end

  test do
    system "#{bin}/program --version"
  end
end
