# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectBackup < Formula
  desc "Fast S3 Tools built in GoLang Using Multiparts and Concurrency"
  homepage ""
  version "0.0.16"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sethkor/connect-backup/releases/download/v0.0.16/connect-backup_0.0.16_Darwin_amd64.tar.gz"
    sha256 "e68358c20c0e50cd6a1fef278be70d1763d6021c134b075040f90812011b0e84"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sethkor/connect-backup/releases/download/v0.0.16/connect-backup_0.0.16_Linux_amd64.tar.gz"
      sha256 "1372cb5241184f213ce1a3eec475d7a7aff794942fd192c826c390aa4c12be26"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sethkor/connect-backup/releases/download/v0.0.16/connect-backup_0.0.16_Linux_arm64.tar.gz"
        sha256 "63e2e16ee47a20973d5274d78baa0dfb906041add7e01c0cdd640185bf5b2475"
      else
        url "https://github.com/sethkor/connect-backup/releases/download/v0.0.16/connect-backup_0.0.16_Linux_armv6.tar.gz"
        sha256 "4a3b406247f73d9f6d25b88288c5d9a086ea12adb3e572ce152f384b3392f54d"
      end
    end
  end

  def install
    bin.install "connect-backup"
  end

  test do
    system "#{bin}/program --version"
  end
end
