# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectBackup < Formula
  desc "Fast S3 Tools built in GoLang Using Multiparts and Concurrency"
  homepage ""
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sethkor/connect-backup/releases/download/v0.0.9/connect-backup_0.0.9_Darwin_amd64.tar.gz"
    sha256 "69a5340ee6bea1a5ae5874e193b5c1ee4d9135bfb2432597185bdbf32cf3fdb1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sethkor/connect-backup/releases/download/v0.0.9/connect-backup_0.0.9_Linux_amd64.tar.gz"
      sha256 "e99b368daf1843ef291791279cc3665c4fd71dbea847f5a13c28fdfb41e5c067"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sethkor/connect-backup/releases/download/v0.0.9/connect-backup_0.0.9_Linux_arm64.tar.gz"
        sha256 "e54ba0e2e8a29095d5f6b8c31bf368c941e95913f057a77ea92e0366e9ac3bd7"
      else
        url "https://github.com/sethkor/connect-backup/releases/download/v0.0.9/connect-backup_0.0.9_Linux_armv6.tar.gz"
        sha256 "c83b55c8e463c77711555d23dda304c87927da5ca457c9c645df2edb9bd90823"
      end
    end
  end

  def install
    bin.install "connect-backup"
  end

  test do
    system "#{bin}/program --version"
  end
end
