# This file was generated by GoReleaser. DO NOT EDIT.
class Lexbelt < Formula
  desc "cli tools for AWS Lex"
  homepage "https://github.com/sethkor/lexbelt/"
  url "https://github.com/sethkor/lexbelt/releases/download/0.0.2/lexbelt_0.0.2_Darwin_amd64.tar.gz"
  version "0.0.2"
  sha256 "b99ffed098ebb1411f04abbea5da46274e2bcf5f821b3670240e30ecc89e5ffa"

  def install
    bin.install "lexbelt"
  end

  test do
    system "#{bin}/program --version"
  end
end
