# This file was generated by GoReleaser. DO NOT EDIT.
class Lexbelt < Formula
  desc "cli tools for AWS Lex"
  homepage "https://github.com/sethkor/lexbelt/"
  url "https://github.com/sethkor/lexbelt/releases/download/0.0.1/lexbelt_0.0.1_Darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "3a3fa3530b2d9919db2dfc41d8291f15544081a8ce1c01fe2025266c8c625102"

  def install
    bin.install "lexbelt"
  end

  test do
    system "#{bin}/program --version"
  end
end
