# This file was generated by GoReleaser. DO NOT EDIT.
class S3kor < Formula
  desc "Fast S3 Tools built in GoLang Using Multiparts and Concurrency"
  homepage ""
  version "0.0.32"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sethkor/s3kor/releases/download/v0.0.32/s3kor_0.0.32_Darwin_amd64.tar.gz"
    sha256 "8acead57bf44625333faf537addbec7330ee651c7d140b4f9d5e69423bc90eb7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sethkor/s3kor/releases/download/v0.0.32/s3kor_0.0.32_Linux_amd64.tar.gz"
      sha256 "ea547de7cd7df78afc6b62fd295471818dddc401ded4abad1589dd6509d54fbe"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sethkor/s3kor/releases/download/v0.0.32/s3kor_0.0.32_Linux_arm64.tar.gz"
        sha256 "57bac1b13b80ed7e1164a751b491e37aebba3f7ed979f7f4f89a9637237b7b2e"
      else
        url "https://github.com/sethkor/s3kor/releases/download/v0.0.32/s3kor_0.0.32_Linux_armv6.tar.gz"
        sha256 "a60e0670004f0d1bb14fc9b6ac31882d2c5ddce0b800a94c760986e071fbba36"
      end
    end
  end

  def install
    bin.install "s3kor"
  end
end
